# Form implementation generated from reading ui file '.\templates\ventanaTiposNP.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventanaTiposNP(object):
    def setupUi(self, ventanaTiposNP):
        ventanaTiposNP.setObjectName("ventanaTiposNP")
        ventanaTiposNP.resize(400, 300)
        self.frame = QtWidgets.QFrame(parent=ventanaTiposNP)
        self.frame.setGeometry(QtCore.QRect(40, 30, 321, 241))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btnAnadirTipo = QtWidgets.QPushButton(parent=self.frame)
        self.btnAnadirTipo.setGeometry(QtCore.QRect(40, 190, 75, 23))
        self.btnAnadirTipo.setObjectName("btnAnadirTipo")
        self.btnEliminarTipo = QtWidgets.QPushButton(parent=self.frame)
        self.btnEliminarTipo.setGeometry(QtCore.QRect(150, 190, 75, 23))
        self.btnEliminarTipo.setObjectName("btnEliminarTipo")
        self.txtTipoEntrada = QtWidgets.QLineEdit(parent=self.frame)
        self.txtTipoEntrada.setGeometry(QtCore.QRect(80, 100, 113, 20))
        self.txtTipoEntrada.setObjectName("txtTipoEntrada")

        self.retranslateUi(ventanaTiposNP)
        QtCore.QMetaObject.connectSlotsByName(ventanaTiposNP)

    def retranslateUi(self, ventanaTiposNP):
        _translate = QtCore.QCoreApplication.translate
        ventanaTiposNP.setWindowTitle(_translate("ventanaTiposNP", "Dialog"))
        self.btnAnadirTipo.setText(_translate("ventanaTiposNP", "Añadir"))
        self.btnEliminarTipo.setText(_translate("ventanaTiposNP", "Eliminar"))
